spring:
  datasource:
    username: root
    password: r00tu$er
    url: jdbc:mysql://localhost:3306/booking_system
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update